trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    cd src/Native/Linux64/build_ALL
    cmake src/Native/Linux64/build_ALL/CMakeLists.txt
    cmake
  displayName: 'Compile Ubuntu library'

- task: PublishPipelineArtifact@0
  displayName: 'Publish Ubuntu artifacts'
  inputs:
    artifactName: 'drop'
    targetPath: 'src/Native/Linux64/build_ALL'