trigger:
- master

jobs:
- job: Build_Windows
  pool:
    vmImage: 'vs2015-win2012r2'
  steps:
  - task: PowerShell@2
    enabled: 'false'
    displayName: Install Windows 10.0.16299.0 SDK
    inputs:
      targetType: 'filePath'
      filePath: 'build/install-sdk.ps1'
      arguments: '16299'
  - task: MSBuild@1
    displayName: 'Compile libijg* libraries'
    inputs:
      solution: "src/Native/Windows64/build_ALL/libijg*.x64.vcxproj"
      platform: 'x64'
      msbuildArchitecture: 'x64'
      configuration: 'Release'
  - task: MSBuild@1
    displayName: 'Compile Windows library'
    inputs:
      solution: "src/Native/Windows64/build_ALL/Efferent.Native-win64.vcxproj"
      platform: 'x64'
      msbuildArchitecture: 'x64'
      configuration: 'Release'
  - task: PublishPipelineArtifact@0
    displayName: 'Publish Windows artifacts'
    inputs:
      artifactName: 'lib'
      targetPath: 'src/Native/Windows64/build_ALL/bin/x64/Release'

- job: Build_Ubuntu
  dependsOn: Build_Windows
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      cd src/Native/Linux64/build_ALL
      cmake ./CMakeLists.txt
      make
    displayName: 'Compile Ubuntu library'
  - task: PublishPipelineArtifact@0
    displayName: 'Publish Ubuntu artifacts'
    inputs:
      artifactName: 'lib'
      targetPath: 'src/Native/Linux64/build_ALL/bin'

